[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "autonomous"
authors = [
    {name = "Steven A Moore", email = "samoore@binghamton.edu"},
]
description = "Containerized application framework built on Flask with additional libraries and tools for rapid development of web applications."
dynamic = ["version", "dependencies"]
readme = "README.md"
requires-python = ">=3.10"
license={file = "LICENSE"}
classifiers=[
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
homepage="https://github.com/Sallenmoore/autonomous"

[project.scripts]
#https://setuptools.pypa.io/en/latest/userguide/entry_point.html
autoapp = "autonomous.cli:createapp"

[tool.setuptools.dynamic]
#https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata
version = {attr = "autonomous.__version__"}
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ["requirements_dev.txt"]}

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]
include = ["autonomous*"]

[tool.pytest.ini_options]
addopts = "--cov=autonomous -rx -l -x" #--no-cov-on-fail --cov-reset
testpaths = [
     "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true


[tool.tox]
legacy_tox_ini = """
    [tox]
    envlist = py310, flake8, mypy
    isolated_build = true

    [gh-actions]
    python = 3.10: py310, mypy, flake8

    [testenv]
    setenv =
        PYTHONPATH = {toxinidir}
    deps =
        -r{toxinidir}/requirements_dev.txt
    commands =
        pytest --basetemp={envtmpdir}

    [testenv:flake8]
    basepython = python3.10
    deps = flake8
    commands = flake8 src tests

    [testenv:mypy]
    basepython = python3.10
    deps = -r{toxinidir}/requirements_dev.txt
    commands = mypy src
"""