[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autonomous"
version = "0.0.34"
authors = [
  { name="Steven Allen Moore", email="samoore@binghamton.edu" },
]
description = "A containerized application framework for python"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  #frontend
  "libsass",

  #network
  "requests",
  "gunicorn",

  ##testing
  "pytest",
  "coverage",
  "pytest-flakes",

  ## data storage
  "tinydb",
  "jsonpickle",

  ## security
  "flask-cors", #https://flask-cors.readthedocs.io/en/latest/

  ## documentation
  "pdoc",
  "pypandoc",

  ## Version Control
  "pygit2",
  "PyGithub",

  ##Framework libs
  "Flask>=2.2",

]

[project.urls]
"Homepage" = "https://github.com/Sallenmoore/autonomous"
"Bug Tracker" = "https://github.com/Sallenmoore/autonomous/issues"